language: r
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  packages: yes
directories:
  - $HOME/bin

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y r-cran-ncdf4

before_script:
  - Rscript -e 'blogdown::install_hugo()'

script:
  - Rscript -e 'blogdown::build_site()'

deploy:
  provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
on:
  branch: master
local_dir: public
fqdn: brycemecum.com
